### ISSUE TITLE
Make PR approval management rules: only our team can approve PRs

### ISSUE THREAD

**Issue by al1ych** [InnoQueue/Backend#123]
See if we can solve this:

- Only our team can approve PR. Other contributors are not allowed to approve any PR.

Apparently, one use-case for this would be open-source projects where we have management (in the form of our team itself) and where we have other contributors that we need to decide on whether or not to approve their changes.

- Other contributors can not merge even if PR is approved.

**Comment by SMore-Napi** [comment]
Please more descriptive name :(

**Comment by al1ych** [comment]
> Please more descriptive name :(

WIP

**Comment by SMore-Napi** [comment]
Please add labels and milestones

**Comment by al1ych** [comment]
After some research found this: https://github.com/orgs/community/discussions/23765

We will add a CODEOWNERS file that :
- automates the process of asking for review
- lets us set Require review from Code Owners to true in the settings so as to solve the first sub-task of this issue(task)
<img width="567" alt="imagen" src="https://user-images.githubusercontent.com/19241702/201714801-04f506e5-a52b-4d07-a9c0-b7b473fc1e0d.png">

**Comment by al1ych** [comment]
Looks like it's working

test branch here: https://github.com/InnoQueue/Backend/pull/125
