### ISSUE TITLE
Write documentation on GitHub

### ISSUE THREAD

**Issue by SMore-Napi** [InnoQueue/Backend#94]
- README.md
- Code comments

Also, follow the structure that was proposed on a lecture:

<p float="left">
<img width="300" src="https://user-images.githubusercontent.com/49106163/198713082-ca8e0179-8d46-4d73-8130-8d5e80a6249a.png"/>
</p>

**Comment by al1ych** [comment]
о ты записал структуру с лекции круто!

**Comment by al1ych** [comment]
suspended

**Comment by al1ych** [comment]
continued
